---
# handlers file for dynatrace_activegate

- name: restart activegate
  ansible.builtin.systemd:
    name: "{{ activegate_service_name }}"
    state: restarted
  become: true
  when: apply_changes | bool
  listen: restart activegate
