---
# handlers file for ubuntu2204_stig

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  when: apply_changes | bool
  listen: restart ssh

- name: restart auditd
  ansible.builtin.command: /usr/sbin/service auditd restart
  register: u_auditd_restart
  changed_when: u_auditd_restart.rc == 0
  when: apply_changes | bool
  listen: restart auditd
