---
# Kernel parameter hardening
# RHEL-09-213xxx / 253xxx / 254xxx | NIST SC-5, SC-7, SI-16

- name: RHEL-09-2xxxxx - Apply kernel sysctl hardening
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-stig.conf
    sysctl_set: "{{ apply_changes | bool }}"
    state: present
    reload: "{{ apply_changes | bool }}"
  loop: "{{ rhel9_sysctl | dict2items }}"
  loop_control:
    label: "{{ item.key }} = {{ item.value }}"
  check_mode: "{{ not (apply_changes | bool) }}"
  register: r_sysctl
  tags:
    - stig_cat2
    - "RHEL-09-253020"
    - "RHEL-09-253080"
    - "RHEL-09-213095"
