---
# handlers file for panos_stig

- name: commit panos
  paloaltonetworks.panos.panos_commit_firewall:
    provider: "{{ panos_provider }}"
  when:
    - apply_changes | bool
    - commit_when_changed | bool
  listen: commit panos
