#!/usr/bin/env python3
"""Compose the collection requirements for one platform, or for the whole repo.

Customers do not take this repository whole. They take the directory for the
platform they run -- cohesity, or pure_storage, or cisco -- and nothing else. An
execution environment built from the union of all 79 requirements.yml files
therefore ships a Pure Storage site the Dragos, Claroty and Veeam collections it
will never load.

This composes the requirements for a named platform instead: every
requirements.yml under that platform's directory, merged to the highest declared
version floor. With --all it composes the union, which is what
execution_environment/requirements.yml holds; CI checks that the two still
agree, so adding a collection to a platform file cannot silently leave the union
behind.

  ./compose-requirements.py --platform cohesity
  ./compose-requirements.py --platform cisco --platform infoblox -o /tmp/req.yml
  ./compose-requirements.py --all
  ./compose-requirements.py --list

A requirements file may carry a "# automation-hub-only: <names>" line, declaring
collections with no stable community-Galaxy release. Markers on the files that
went into a composition are carried onto its output, so a platform that does not
depend on a hub-only collection does not inherit the warning.
"""
from __future__ import annotations

import argparse
import os
import re
import sys

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EE_DIR = os.path.join(REPO_ROOT, "execution_environment")
MARKER = re.compile(r"^#\s*automation-hub-only:\s*(.+)$", re.M)


def platform_dirs() -> list[str]:
    """Top-level directories that declare at least one requirements.yml."""
    found = set()
    for name in sorted(os.listdir(REPO_ROOT)):
        path = os.path.join(REPO_ROOT, name)
        if not os.path.isdir(path) or name.startswith(".") or path == EE_DIR:
            continue
        for dirpath, _, filenames in os.walk(path):
            if "requirements.yml" in filenames:
                found.add(name)
                break
    return sorted(found)


def requirement_files(platforms: list[str]) -> list[str]:
    files = []
    for platform in platforms:
        root = os.path.join(REPO_ROOT, platform)
        if not os.path.isdir(root):
            raise SystemExit(
                "no such platform directory: %s\n"
                "run with --list to see the platforms that declare requirements" % platform
            )
        for dirpath, _, filenames in os.walk(root):
            if "requirements.yml" in filenames:
                files.append(os.path.join(dirpath, "requirements.yml"))
    return sorted(files)


def version_key(spec: str | None) -> tuple:
    """Sort key for a ">=X.Y.Z" floor. An absent floor sorts lowest."""
    if not spec:
        return ()
    digits = re.sub(r"^[<>=!~^\s]+", "", str(spec)).strip()
    parts = []
    for chunk in digits.split("."):
        number = re.match(r"\d+", chunk)
        parts.append(int(number.group()) if number else 0)
    return tuple(parts)


def compose(platforms: list[str]) -> tuple[dict, list[str], set[str]]:
    """Merge every requirements.yml under `platforms` to the highest floor."""
    floors: dict[str, str | None] = {}
    hub_only: set[str] = set()
    files = requirement_files(platforms)

    for path in files:
        text = open(path).read()
        for match in MARKER.finditer(text):
            hub_only.update(match.group(1).split())

        document = yaml.safe_load(text) or {}
        for entry in document.get("collections") or []:
            if isinstance(entry, str):
                name, version = entry, None
            else:
                name, version = entry.get("name"), entry.get("version")
            if not name:
                continue
            if name not in floors or version_key(version) > version_key(floors[name]):
                floors[name] = version

    collections = []
    for name in sorted(floors):
        entry = {"name": name}
        if floors[name]:
            entry["version"] = floors[name]
        collections.append(entry)
    return {"collections": collections}, files, hub_only & set(floors)


def render(platforms: list[str], everything: bool) -> str:
    document, files, hub_only = compose(platforms)
    scope = "every platform in this repository" if everything else ", ".join(platforms)

    lines = [
        "---",
        "# Collection requirements for: %s" % scope,
        "#",
        "# Generated by execution_environment/compose-requirements.py -- do not",
        "# edit by hand. It merges the %d requirements.yml file(s) below to the" % len(files),
        "# highest declared version floor. Change a platform's own",
        "# requirements.yml and regenerate.",
        "#",
    ]
    for path in files:
        lines.append("#   %s" % os.path.relpath(path, REPO_ROOT))
    lines.append("#")

    if hub_only:
        names = " ".join(sorted(hub_only))
        lines += [
            "# automation-hub-only: %s" % names,
            "#",
            "# The marker above follows the repo convention read by",
            "# scripts/generate_online_baseline.sh: these collections have no stable",
            "# release on community Galaxy (certified builds ship only from Red Hat",
            "# Automation Hub). Building against Galaxy alone will fail to resolve",
            "# them -- configure your Automation Hub server and token in ansible.cfg",
            "# before building, or drop them if you do not manage AAP itself.",
            "#",
        ]

    lines.append("")

    # Rendered by hand rather than through yaml.safe_dump: the repo's yamllint
    # config sets indent-sequences: true, and safe_dump emits indentless block
    # sequences. Names are FQCNs and versions are ">=X.Y.Z", so the only value
    # needing quotes is the version.
    if not document["collections"]:
        lines.append("collections: []")
    else:
        lines.append("collections:")
        for entry in document["collections"]:
            lines.append("  - name: %s" % entry["name"])
            if "version" in entry:
                lines.append('    version: "%s"' % entry["version"])
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compose collection requirements for one platform, or for the whole repo.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--platform", action="append", default=[], metavar="NAME",
                        help="platform directory to include; repeat for several")
    parser.add_argument("--all", action="store_true",
                        help="include every platform (the union in requirements.yml)")
    parser.add_argument("--list", action="store_true",
                        help="list the platforms that declare requirements and exit")
    parser.add_argument("-o", "--output", metavar="PATH",
                        help="write here instead of stdout")
    args = parser.parse_args()

    if args.list:
        try:
            for name in platform_dirs():
                count = len(requirement_files([name]))
                print("%-26s %d requirements.yml" % (name, count))
            sys.stdout.flush()
        except BrokenPipeError:
            # Piping into head/less closes stdout early; that is not an error.
            os.dup2(os.open(os.devnull, os.O_WRONLY), sys.stdout.fileno())
        return 0

    if args.all and args.platform:
        parser.error("--all and --platform are mutually exclusive")
    if not args.all and not args.platform:
        parser.error("give --platform NAME (repeatable), or --all; --list shows the names")

    platforms = platform_dirs() if args.all else args.platform
    text = render(platforms, everything=args.all)

    if args.output:
        with open(args.output, "w") as handle:
            handle.write(text)
        document, files, _ = compose(platforms)
        print("==> %s: %d collection(s) from %d requirements.yml"
              % (args.output, len(document["collections"]), len(files)), file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
