#!/usr/bin/env bash
# Resolve the version floors in requirements.yml into exact pins
# (requirements-lock.yml) so every agency builds a byte-identical collection
# set. Run on a machine that can reach galaxy.ansible.com (and, for the
# automation-hub-only collections, a configured Automation Hub server).
#
# Commit the resulting requirements-lock.yml; build.sh prefers it when present.
#
# Mirrors the repo convention of scripts/generate_online_baseline.sh: install
# failures for collections named on the "# automation-hub-only:" marker line
# are expected on a Galaxy-only machine and reported, not fatal.
set -euo pipefail

cd "$(dirname "$0")"

command -v ansible-galaxy >/dev/null 2>&1 || {
  echo "ansible-galaxy is not available. Install ansible-core first:" >&2
  echo "  pip install ansible-core==2.19.11" >&2
  exit 1
}

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

hub_only="$(grep -oP '^# automation-hub-only: \K.*' requirements.yml || true)"

# Try the full set first; if Automation Hub is not configured, retry without
# the hub-only collections so a Galaxy-only machine can still produce a lock.
req="requirements.yml"
if ! ansible-galaxy collection download -r "$req" -p "$workdir/dl"; then
  if [ -n "$hub_only" ]; then
    echo "==> Full download failed; retrying without automation-hub-only collections: $hub_only"
    python3 - "$req" "$workdir/req-galaxy-only.yml" $hub_only <<'PYEOF'
import sys, yaml
src, dst, skip = sys.argv[1], sys.argv[2], set(sys.argv[3:])
data = yaml.safe_load(open(src))
data["collections"] = [c for c in data["collections"] if c.get("name") not in skip]
yaml.safe_dump(data, open(dst, "w"), sort_keys=False)
PYEOF
    rm -rf "$workdir/dl"
    ansible-galaxy collection download -r "$workdir/req-galaxy-only.yml" -p "$workdir/dl"
    echo "NOTE: $hub_only are NOT in the lock; they resolve from Automation Hub at build time." >&2
  else
    exit 1
  fi
fi

# 'collection download' writes a requirements.yml in the download dir pinned
# to the exact versions it fetched (including transitive dependencies).
{
  echo "---"
  echo "# Exact-version lock generated by generate-lock.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# Do not edit by hand; regenerate after changing requirements.yml."
  if [ -n "$hub_only" ]; then
    echo "# automation-hub-only collections (resolved at build time, not locked): $hub_only"
  fi
  tail -n +2 "$workdir/dl/requirements.yml" \
    | sed -E 's#source: .*#source: https://galaxy.ansible.com#'
} > requirements-lock.yml

echo "==> Wrote requirements-lock.yml ($(grep -c 'name:' requirements-lock.yml) collections, dependencies included)"
echo "==> Review and commit it: git add execution_environment/requirements-lock.yml"
