#!/usr/bin/env bash
# Resolve version floors into exact pins so every agency builds a byte-identical
# collection set.
#
#   ./generate-lock.sh --platform cohesity   -> requirements-lock-cohesity.yml
#   ./generate-lock.sh --platform cisco --platform infoblox
#   ./generate-lock.sh --all                 -> requirements-lock.yml
#   ./generate-lock.sh --list                -> the platforms you can name
#
# Lock files are named to match the image build.sh produces from the same
# arguments, so a platform's lock cannot be applied to another platform's image
# by accident.
#
# Run on a machine that can reach galaxy.ansible.com (and, for the
# automation-hub-only collections, a configured Automation Hub server). Commit
# the result; build.sh prefers it when present.
#
# Mirrors the repo convention of scripts/generate_online_baseline.sh: install
# failures for collections named on a "# automation-hub-only:" marker line are
# expected on a Galaxy-only machine and reported, not fatal.
set -euo pipefail

cd "$(dirname "$0")"

platforms=()
all=false

while [ $# -gt 0 ]; do
  case "$1" in
    --platform) platforms+=("${2:?--platform needs a name}"); shift 2 ;;
    --all)      all=true; shift ;;
    --list)     exec ./compose-requirements.py --list ;;
    -h|--help)  sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)          echo "unknown argument: $1 (try --help)" >&2; exit 2 ;;
  esac
done

if $all && [ "${#platforms[@]}" -gt 0 ]; then
  echo "--all and --platform are mutually exclusive" >&2; exit 2
fi
if ! $all && [ "${#platforms[@]}" -eq 0 ]; then
  echo "Name what to lock: --platform <name> (repeatable), or --all." >&2
  echo "Run './generate-lock.sh --list' to see the platforms that declare requirements." >&2
  exit 2
fi

command -v ansible-galaxy >/dev/null 2>&1 || {
  echo "ansible-galaxy is not available. Install ansible-core first:" >&2
  echo "  pip install ansible-core==2.19.11" >&2
  exit 1
}

if $all; then
  slug=""
  scope="every platform"
  compose_args=(--all)
else
  known="$(./compose-requirements.py --list | awk '{print $1}')"
  for p in "${platforms[@]}"; do
    grep -qx -- "$p" <<<"$known" || {
      echo "no such platform: $p (try --list)" >&2; exit 2; }
  done
  slug="-$(IFS=-; echo "${platforms[*]}")"
  scope="$(IFS=', '; echo "${platforms[*]}")"
  compose_args=()
  for p in "${platforms[@]}"; do compose_args+=(--platform "$p"); done
fi
out="requirements-lock${slug}.yml"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

req="$workdir/requirements.yml"
./compose-requirements.py "${compose_args[@]}" -o "$req"

if ! grep -q '^  - name:' "$req"; then
  echo "==> $scope declares no collections; nothing to lock." >&2
  exit 0
fi

hub_only="$(grep -oP '^# automation-hub-only: \K.*' "$req" || true)"

# Try the full set first; if Automation Hub is not configured, retry without the
# hub-only collections so a Galaxy-only machine can still produce a lock.
if ! ansible-galaxy collection download -r "$req" -p "$workdir/dl"; then
  if [ -n "$hub_only" ]; then
    echo "==> Full download failed; retrying without automation-hub-only collections: $hub_only"
    # The marker is a space-separated list; split it into separate arguments
    # rather than passing one string, which would skip nothing.
    read -r -a hub_only_names <<<"$hub_only"
    python3 - "$req" "$workdir/req-galaxy-only.yml" "${hub_only_names[@]}" <<'PYEOF'
import sys, yaml
src, dst, skip = sys.argv[1], sys.argv[2], set(sys.argv[3:])
data = yaml.safe_load(open(src))
data["collections"] = [c for c in data["collections"] if c.get("name") not in skip]
yaml.safe_dump(data, open(dst, "w"), sort_keys=False)
PYEOF
    rm -rf "$workdir/dl"
    ansible-galaxy collection download -r "$workdir/req-galaxy-only.yml" -p "$workdir/dl"
    echo "NOTE: $hub_only are NOT in the lock; they resolve from Automation Hub at build time." >&2
  else
    exit 1
  fi
fi

# 'collection download' writes a requirements.yml in the download dir pinned to
# the exact versions it fetched, including transitive dependencies.
{
  echo "---"
  echo "# Exact-version lock for: $scope"
  echo "# Generated by generate-lock.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# Do not edit by hand; regenerate after changing a platform's requirements.yml."
  echo "# build.sh reads this when invoked with the same --platform/--all arguments."
  if [ -n "$hub_only" ]; then
    echo "# automation-hub-only collections (resolved at build time, not locked): $hub_only"
  fi
  tail -n +2 "$workdir/dl/requirements.yml" \
    | sed -E 's#source: .*#source: https://galaxy.ansible.com#'
} > "$out"

echo "==> Wrote $out ($(grep -c 'name:' "$out") collections, dependencies included)"
echo "==> Review and commit it: git add execution_environment/$out"
