---
# Kernel parameter hardening
# RHEL-08-010xxx / 253xxx / 254xxx | NIST SC-5, SC-7, SI-16

- name: RHEL-08-0xxxxx - Apply kernel sysctl hardening
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-stig.conf
    sysctl_set: "{{ apply_changes | bool }}"
    state: present
    reload: "{{ apply_changes | bool }}"
  loop: "{{ rhel8_sysctl | dict2items }}"
  loop_control:
    label: "{{ item.key }} = {{ item.value }}"
  check_mode: "{{ not (apply_changes | bool) }}"
  register: r_sysctl
  tags:
    - stig_cat2
    - "RHEL-08-040209"
    - "RHEL-08-040285"
    - "RHEL-08-010430"
