---
# handlers file for cisco_ios_xe_l2_stig

- name: save running-config
  cisco.ios.ios_config:
    save_when: modified
  when:
    - apply_changes | bool
    - save_config_when_changed | bool
  listen: save running-config
