---
# Example overrides for mongodb_stig (-e @vars.example.yml).
apply_changes: false
mongodb_storage_dbpath: /var/lib/mongo
mongodb_systemlog_path: /var/log/mongodb/mongod.log
mongodb_bind_ip: "10.0.0.99"
mongodb_tls_cert_key_file: /etc/ssl/mongodb.pem
mongodb_tls_ca_file: /etc/ssl/mongodbCA.pem
