---
# tasks file for zos_netview_tss_stig

- name: Set generic assessment context
  ansible.builtin.set_fact:
    zos_catalog: "{{ zos_netview_catalog }}"
    zos_slug: "zos_netview_tss_stig"
  tags: [always]

- name: Generate checklist and (optionally) run live read-only assessment
  ansible.builtin.import_tasks: assess.yml
  tags: [always]
