---
# handlers file for sl1_platform_config

- name: Restart SL1 services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - sl1_em7
    - sl1_mysql
    - sl1_memcached
    - sl1_elasticsearch
  listen: "Restart SL1 services"
