---
galaxy_info:
  role_name: sdwan_vmanage_config
  author: "Fourth Estate Infrastructure Team"
  description: >
    Cisco SD-WAN vManage Configuration.
    Configures user groups, feature templates, device templates, and SD-WAN policies.
  company: "Fourth Estate"
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - cisco
    - sdwan
    - catalystwan
    - vmanage
    - templates
    - policies
    - fourth_estate

dependencies: []

collections:
  - ansible.builtin
  - ansible.utils
