---
galaxy_info:
  role_name: aap_controller_credentials
  author: Fourth Estate Infrastructure Team
  description: AAP controller credential types and credentials as code
  company: Fourth Estate
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - ansible
    - aap
    - controller
    - configuration_as_code
    - rbac
    - compliance

dependencies: []

collections:
  - infra.controller_configuration
