---
# handlers file for mongodb_stig

- name: restart mongod
  ansible.builtin.systemd:
    name: "{{ mongodb_service_name }}"
    state: restarted
  when:
    - apply_changes | bool
    - restart_mongod_when_changed | bool
  listen: restart mongod
