---
- name: Ensure artifacts dir
  ansible.builtin.file:
    path: "{{ artifacts_dir }}"
    state: directory
    mode: "0755"

- import_tasks: 10_tls.yml
- import_tasks: 20_sso.yml
- import_tasks: 30_api_tokens.yml
- import_tasks: 40_auth.yml
