#!/usr/bin/env python3
"""Stamp a VERSION.yml into every platform directory.

Customers do not take this repository whole. They take the directory for the
platform they run -- cohesity/, or pure_storage/, or cisco/ -- and copy it into
their own environment. Once it is there, nothing in it says where it came from
or which release it is, so there is no way to answer the two questions that
matter after a security fix ships:

    which version am I running, and is there a newer one?

This writes that answer into each platform directory, as
<platform>/VERSION.yml. Run it when cutting a release, before tagging:

    ./scripts/stamp_platform_versions.py --release 1.2.0
    git add '*/VERSION.yml' && git commit -m "Stamp platform versions for 1.2.0"
    git tag 1.2.0

    ./scripts/stamp_platform_versions.py --check     # what CI runs

--check verifies that every platform directory has a marker, that each names
its own directory, and that the schema is complete. It deliberately does NOT
check the release string against the latest tag: between releases the marker
names the release a snapshot was last cut from, which is the honest answer, and
a freshness check would fail every commit.
"""
from __future__ import annotations

import argparse
import datetime
import os
import subprocess
import sys

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO_URL = "https://github.com/Koga1985/Fourth-Estate-Ansible-Playbooks"
MARKER = "VERSION.yml"

# Directories at the top level that are not platforms: repo infrastructure a
# customer never takes on its own.
NOT_PLATFORMS = {"docs", "scripts", "execution_environment", "callback_plugins",
                 "molecule", "group_vars", "inventory", "library", "filter_plugins"}

REQUIRED_KEYS = ["platform", "release", "commit", "stamped", "repository",
                 "documentation", "check_for_updates"]


def _runnable(path: str) -> bool:
    """A directory a customer could copy out and run: it declares its own
    collection requirements and ships automation to run with them."""
    if not os.path.exists(os.path.join(path, "requirements.yml")):
        return False
    return any(os.path.exists(os.path.join(path, sub))
               for sub in ("roles", "tasks", "playbooks", "site.yml"))


def platform_dirs() -> list[str]:
    """Directories a customer takes on their own, as repo-relative paths.

    Usually a top-level directory. databases/ is the exception: it is a
    container, and db2, mysql, oracle and postgresql under it are each
    separately runnable, each with their own requirements.yml, site.yml and
    inventory.example. A customer takes databases/postgresql, never databases.
    """
    out = []
    for name in sorted(os.listdir(REPO_ROOT)):
        path = os.path.join(REPO_ROOT, name)
        if not os.path.isdir(path) or name.startswith(".") or name in NOT_PLATFORMS:
            continue
        if _runnable(path):
            out.append(name)
            continue
        for child in sorted(os.listdir(path)):
            child_path = os.path.join(path, child)
            if os.path.isdir(child_path) and _runnable(child_path):
                out.append("%s/%s" % (name, child))
    return out


def git(*args: str) -> str:
    try:
        return subprocess.check_output(["git", "-C", REPO_ROOT, *args],
                                       text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return ""


def render(platform: str, release: str, commit: str, stamped: str) -> str:
    ref = release if release != "unreleased" else "main"
    return f"""---
# Which release of the Fourth Estate playbooks this directory came from.
#
# Generated by scripts/stamp_platform_versions.py -- do not edit by hand.
#
# You are probably reading this because you copied this one directory into your
# own environment and need to know what you have. That is the supported way to
# consume this repository; this file is how a copied directory stays traceable
# back to a release, and to the security advisories that reference one.

platform: {platform}
release: "{release}"
commit: {commit}
stamped: "{stamped}"

repository: {REPO_URL}
documentation: {REPO_URL}/tree/{ref}/docs
check_for_updates: {REPO_URL}/releases

# What changed between your release and the current one:
#   {REPO_URL}/blob/{ref}/docs/CHANGELOG.md
#
# Limitations that apply to this platform, including anything a playbook here
# cannot do safely on its own:
#   {REPO_URL}/blob/{ref}/docs/KNOWN_LIMITATIONS.md
"""


def do_stamp(release: str) -> int:
    commit = git("rev-parse", "HEAD") or "unknown"
    stamped = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    for platform in platform_dirs():
        path = os.path.join(REPO_ROOT, platform, MARKER)
        with open(path, "w") as handle:
            handle.write(render(platform, release, commit, stamped))
        print("  stamped %s" % os.path.relpath(path, REPO_ROOT))
    print("==> %d platform(s) stamped at release %s" % (len(platform_dirs()), release))
    return 0


def do_check() -> int:
    problems = []
    for platform in platform_dirs():
        path = os.path.join(REPO_ROOT, platform, MARKER)
        if not os.path.exists(path):
            problems.append("%s/%s is missing" % (platform, MARKER))
            continue
        try:
            doc = yaml.safe_load(open(path)) or {}
        except Exception as exc:
            problems.append("%s/%s does not parse: %s" % (platform, MARKER, exc))
            continue
        for key in REQUIRED_KEYS:
            if not doc.get(key):
                problems.append("%s/%s has no '%s'" % (platform, MARKER, key))
        if doc.get("platform") and doc["platform"] != platform:
            problems.append("%s/%s says platform: %s" % (platform, MARKER, doc["platform"]))

    if problems:
        print("Platform version markers are not in order:\n")
        for p in problems:
            print("  %s" % p)
        print("\nRegenerate them with:")
        print("  ./scripts/stamp_platform_versions.py --release <version>")
        return 1
    print("All %d platform directories carry a valid %s." % (len(platform_dirs()), MARKER))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Stamp or verify the per-platform version marker.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--release", metavar="VERSION",
                       help="release string to stamp, e.g. 1.2.0")
    group.add_argument("--check", action="store_true",
                       help="verify every platform has a valid marker (CI)")
    group.add_argument("--list", action="store_true",
                       help="list the platform directories that get a marker")
    args = parser.parse_args()

    if args.list:
        for p in platform_dirs():
            print(p)
        return 0
    if args.check:
        return do_check()
    return do_stamp(args.release)


if __name__ == "__main__":
    sys.exit(main())
