---
# handlers file for apache_web_server_srg

- name: reload apache
  ansible.builtin.systemd:
    name: "{{ apache_service_name }}"
    state: reloaded
  when: apply_changes | bool
  listen: reload apache
