---
# handlers file for postgresql_replication

- name: reload postgresql
  ansible.builtin.service:
    name: "postgresql-{{ postgresql_version }}"
    state: reloaded

- name: restart postgresql
  ansible.builtin.service:
    name: "postgresql-{{ postgresql_version }}"
    state: restarted
