---
# handlers file for db2_stig

- name: restart db2 instance
  ansible.builtin.shell: "{{ db2_clp }} db2stop force && {{ db2_clp }} db2start"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ db2_instance_owner }}"
  register: db2_restart
  changed_when: db2_restart.rc == 0
  when: apply_changes | bool
  listen: restart db2 instance
